#!/usr/bin/env sh

git_version () {
    git describe --tags --exact-match 2>/dev/null || \
        printf %s\\n "git-$(git describe --always --dirty)"
}

if [ "$1" = "build" ]; then
    pkg="$2"
    case "$pkg" in
    micro|fastmod)
        cd "src/${pkg}"
        v="$(git_version)"
        make
        cd -
        rm -f "${pkg}-"*
        ln -sv "src/${pkg}/${pkg}" "${pkg}-${v}"
        ln -sv "${pkg}-${v}" "$pkg"
        ;;
    *)
        echo "packages:"; ls -1 src
    esac
fi
