#!/usr/bin/env sh

# it would be nice to find out how to or modify packages such that
# i can embed the go/rust/etc. version into their help when building

git_version () {
    git describe --tags --exact-match 2>/dev/null || \
        printf %s\\n "git-$(git describe --always --dirty)"
}

if [ "$1" = "build" ]; then
    shift
    for pkg in "$@"; do
        bin="$pkg"
        case "$pkg" in
        micro|fastmod|fd)
            cd "src/${pkg}"
            make
            ;;
        ripgrep)
            cd src/ripgrep
            make
            bin=rg
            ;;
        tmux)
            cd src/tmux
            make || {
                sh autogen.sh
                CFLAGS="-O3 -flto -march=native" ./configure
                make
            }
            ;;
        sym-prototype)
            cd src/sym-prototype
            bin=sym
            ;;
        ydiff)
            cd src/ydiff
            ln -s ydiff.py git-ydiff
            bin=git-ydiff
            ;;
        alacritty)
            cd src/alacritty
            # TODO: macos vs. linux conditionals
            # under linux, would like to build with only wayland feature
            make
            bin=alacritty-bin
            # macos only (needed to launch from spotlight)
            cat <<EOF > "${bin}.command"
#!/bin/sh
"${PWD}/${bin}" &
disown && exit 0
EOF
            chmod u+x "${bin}.command"
            ;;
        *)
            echo "package ${pkg} not found"
            continue
        esac

        v="$(git_version)"
        cd -
        rm -f "${bin}-"*
        ln -sv "src/${pkg}/${bin}" "${bin}-${v}"
        ln -svf "${bin}-${v}" "$bin"
    done
fi
