#!/usr/bin/env sh

# it would be nice to find out how to or modify packages such that
# i can embed the go/rust/etc. version into their help when building

git_version () {
    printf '%s-%s\n' \
        "$(git describe --tags --abbrev=0 2>/dev/null || printf '%s' 'git')" \
        "$(git rev-parse --short HEAD)"
}

if [ "$1" = "build" ]; then
    shift
    for pkg in "$@"; do
        bins="$pkg"
        case "$pkg" in
        fastmod|srv|direnv|restic)
            cd "src/${pkg}"
            make
            ;;
        micro)
            cd "src/${pkg}"
            make
            strip ./micro
            ./micro -plugin install editorconfig
            ;;
        ripgrep)
            cd "src/${pkg}"
            RUSTFLAGS="-Ctarget-cpu=native" cargo build --release
            mv target/release/rg rg
            strip rg
            bins=rg
            ;;
        fd|delta|zenith)
            cd "src/${pkg}"
            RUSTFLAGS="-Ctarget-cpu=native" cargo build --release
            mv "target/release/${pkg}" "$pkg"
            #strip "$pkg"
            ;;
        tmux)
            # needs: autoconf, automake, bison
            cd "src/${pkg}"
            make -j"$(nproc)" || {
                sh autogen.sh
                CC=gcc CFLAGS="-O2 -flto -pipe -march=native" ./configure
                make clean
                make -j"$(nproc)"
            }
            strip tmux
            ;;
        ncdu)
            cd "src/${pkg}"
            make -j"$(nproc)" || {
                autoreconf -i
                CC=gcc CFLAGS="-O2 -flto -pipe -march=native" ./configure
                make clean
                make -j"$(nproc)"
            }
            strip ncdu
            ;;
        sym-prototype)
            cd "src/${pkg}"
            bins=sym
            ;;
        pulsemixer)
            cd "src/${pkg}"
            ;;
        alacritty)
            # needs fontconfig
            cd "src/${pkg}"
            # TODO: macos vs. linux conditionals
            # under linux, would like to build with only wayland feature
            make
            bins=alacritty-bin
            # macos only (needed to launch from spotlight)
            if [ "$(uname)" = 'Darwin' ]; then
                cat <<EOF > "alacritty.command"
#!/bin/sh
"${HOME}/bin/alacritty-bin" &
disown && exit 0
EOF
                chmod u+x "alacritty.command"
            fi
            ;;
        *)
            echo "package ${pkg} not found"
            continue
        esac

        v="$(git_version)"
        cd -
        for bin in $bins; do
            rm -f "${bin}-"*
            ln -sv "src/${pkg}/${bin}" "${bin}-${v}"
            ln -svf "${bin}-${v}" "$bin"
        done
    done
fi
